package application.io.spring.utils;

/**
 *	This is an utility class auto-generated by underlying framework. <br/>
 *	<p>
 *  This class can be modified according to business requirement.
 *  </p>
 *	
 * 	@ClassName: RedisKeyPrefixUtils
 *  @Description redis缓存前缀公共类，避免redis缓存key重复，建议key值所需的前缀都在此类配置
 *	@author vinsy
 *  @date 2018年7月11日 下午4:24:24 
 *	
 *	@Description 以下仅以es-preferential-server中的RedisKeyPrefixUtil作为例子，更多用法参考es-api-server和es-manger-server
 *	@author vinsy
 *  @date 2018/03/23
 */
public class RedisKeyPrefixUtils {

	//文件存入缓存的key前缀：以下值来自es-preferential-server，仅作举例用
	public static final String fileKeyPrefix="preferential-file-";

	//前端传过来的json真正业务逻辑的json key：以下值来自es-preferential-server，仅作举例用
	public static final String jsonDateKey = "data";

	public static final String AuthorizationResource = "AuthorizationResource";

	public static final String AuthorizationRole = "AuthorizationRole";

	public static final String AuthorizationRoleResource = "AuthorizationRoleResource";

	public static final String AuthorizationUser = "AuthorizationUser";

	public static final String AuthorizationUserRole = "AuthorizationUserRole";

	public static final String AuthorizationUserRoleResourceData = "AuthorizationUserRoleResourceData";
}
