spring:
  profiles: local
  
server:
  port: 13579
  context-path: /spring-boot-application
  servlet-path: /api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/xyes_production
    username: postgres
    password: postgres
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    maximum-pool-size: 30
    max-active: 15