package application.io.spring.authorization.business.provider.dao;

import application.io.spring.core.base.provider.dao.BaseDAO;
import application.io.spring.authorization.business.api.model.AuthorizationUser;
import application.io.spring.authorization.business.api.vo.AuthorizationUserResourceVo;
import application.io.spring.authorization.business.api.vo.AuthorizationUserRoleVo;

import java.util.List;
import java.util.Map;

/**
 *	This is a DAO interface auto-generated by underlying framework. <br/>
 *	<p>
 *  This interface can be modified according to business requirement.
 *  </p>
 *	
 *  @Description 该DAO接口的内容可根据实际业务需求调整
 *	@author vinsy
 *  @date 2018/03/23
 */
public interface AuthorizationUserDAO extends BaseDAO<AuthorizationUser> {

	// 根据jsonb条件查询分页数据
	List<AuthorizationUser> getJsonbPageableList(Map<String,Object> params);

	// 根据jsonb条件查询总数量
	long getJsonbListCount(Map<String, Object> params);

	public List<AuthorizationUserRoleVo> selectAllUserRolesByName(Map<String, Object> params) throws Exception;

	public List<AuthorizationUserRoleVo> selectAllUserRolesByNameV2(Map<String, Object> params) throws Exception;
	
	public List<AuthorizationUserResourceVo> selectAllUserResourcesByName(Map<String, Object> params) throws Exception;
	
	public List<AuthorizationUserResourceVo> selectAllUserResourcesByNameV2(Map<String, Object> params) throws Exception;
}
