package application.io.spring.bottomware.authorization.business.api.service;

import application.io.spring.bottomware.authorization.business.api.model.AuthorizationUser;
import application.io.spring.bottomware.authorization.business.api.vo.AuthorizationUserResourceVo;
import application.io.spring.bottomware.authorization.business.api.vo.AuthorizationUserRoleVo;
import application.io.spring.core.base.api.service.BaseService;
import application.io.spring.core.base.api.vo.PageVo;

import java.util.List;

/**
 *	This is a service interface auto-generated by underlying framework. <br/>
 *	<p>
 *  This interface can be modified according to business requirement.
 *  </p>
 *	
 *  @Description 该服务接口的内容可根据实际业务需求调整
 *	@author vinsy
 *  @date 2018/03/23
 */
public interface AuthorizationUserService extends BaseService<AuthorizationUser> {

	// 根据jsonb条件查询分页数据
	public PageVo<AuthorizationUser> getJsonbPageableList(AuthorizationUser authorizationUser,Long offset, Long limit, String orderby);

	public List<AuthorizationUserRoleVo> selectAllUserRolesByName(AuthorizationUser query);
	
	public List<AuthorizationUserRoleVo> selectAllUserRolesByNameV2(AuthorizationUser query);

	public List<AuthorizationUserResourceVo> selectAllUserResourcesByName(AuthorizationUser query);
	
	public List<AuthorizationUserResourceVo> selectAllUserResourcesByNameV2(AuthorizationUser query);
}
