package application.io.spring.authorization.business.api.model;

import application.io.spring.core.base.api.model.Identifiable;
import java.util.Date;

import lombok.Getter;
import lombok.Setter;

/**
 *	This is a Java bean auto-generated by underlying framework. <br/>
 *	<p>
 *  This Java bean corresponds to a table in a database.
 *  </p>
 *	
 *  @Description 每个模型类对应一个数据库中的一张表
 *	@author vinsy
 *  @date 2018/03/23
 */
@Setter
@Getter
public class AuthorizationRole extends Identifiable {

	private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * 备注
     * </pre>
     * 
     */
    private String remark;

    /**
     * <pre>
     * 角色显示顺序
     * </pre>
     * 
     */
    private Long seq;

    /**
     * <pre>
     * 创建时间
     * </pre>
     * 
     */
    private Date createTime;

    /**
     * <pre>
     * 角色编码:admin
     * </pre>
     * 
     */
    private String code;

    /**
     * <pre>
     * 角色名称
     * </pre>
     * 
     */
    private String name;

    /**
     * <pre>
     * 角色分组
     * </pre>
     * 
     */
    private String roleGroup;

    /**
     * <pre>
     * </pre>
     * 
     */
    private Object extendedField;

    /**
     * <pre>
     * </pre>
     * 
     */
    private Date updateTime;

    /**
     * <pre>
     * 父资源编号
     * </pre>
     * 
     */
    private Long parentId;

    /**
     * <pre>
     * 左值：比父节点左值大
     * </pre>
     * 
     */
    private Long leftValue;

    /**
     * <pre>
     * 右值：比父节点右值小
     * </pre>
     * 
     */
    private Long rightValue;

    /**
     * <pre>
     * 用于取代parent_id
     * </pre>
     * 
     */
    private String parentNode;

    /**
     * <pre>
     * 用于取代left_value
     * </pre>
     * 
     */
    private String leftNode;

    /**
     * <pre>
     * 用于取代right_value
     * </pre>
     * 
     */
    private String rightNode;

    /**
     * <pre>
     * 权限模块角色唯一ID：可取代主键ID用于查询或关联等
     * </pre>
     * 
     */
    private String roleId;

}
