package application.io.spring.bottomware.authorization.business.api.model;

import application.io.spring.core.base.api.model.Identifiable;
import java.util.Date;

import lombok.Getter;
import lombok.Setter;

/**
 *	This is a Java bean auto-generated by underlying framework. <br/>
 *	<p>
 *  This Java bean corresponds to a table in a database.
 *  </p>
 *	
 *  @Description 每个模型类对应一个数据库中的一张表
 *	@author vinsy
 *  @date 2018/03/23
 */
@Setter
@Getter
public class AuthorizationResource extends Identifiable {

	private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * 资源名称
     * </pre>
     * 
     */
    private String name;

    /**
     * <pre>
     * 资源信息
     * </pre>
     * 
     */
    private String resource;

    /**
     * <pre>
     * 资源分类(LEAF;BOTTOM)：子节点，叶子节点（不能创建下一级目录）
     * </pre>
     * 
     */
    private String resourceType;

    /**
     * <pre>
     * 资源序列
     * </pre>
     * 
     */
    private Long seq;

    /**
     * <pre>
     * 父资源编号
     * </pre>
     * 
     */
    private Long parentId;

    /**
     * <pre>
     * 左值：比父节点左值大
     * </pre>
     * 
     */
    private Long leftValue;

    /**
     * <pre>
     * 右值：比父节点右值小
     * </pre>
     * 
     */
    private Long rightValue;

    /**
     * <pre>
     * 编码
     * </pre>
     * 
     */
    private String code;

    /**
     * <pre>
     * 备注
     * </pre>
     * 
     */
    private String remark;

    /**
     * <pre>
     * </pre>
     * 
     */
    private Object extendedField;

    /**
     * <pre>
     * </pre>
     * 
     */
    private Date createTime;

    /**
     * <pre>
     * </pre>
     * 
     */
    private Date updateTime;

    /**
     * <pre>
     * 权限模块资源唯一ID：可取代主键ID用于查询或关联等
     * </pre>
     * 
     */
    private String resourceId;

    /**
     * <pre>
     * 用于取代parent_id
     * </pre>
     * 
     */
    private String parentNode;

    /**
     * <pre>
     * 用于取代left_value
     * </pre>
     * 
     */
    private String leftNode;

    /**
     * <pre>
     * 用于取代right_value
     * </pre>
     * 
     */
    private String rightNode;

}
