package application.io.spring.bottomware.authorization.business.api.model;

import application.io.spring.core.base.api.model.Identifiable;
import java.util.Date;

import lombok.Getter;
import lombok.Setter;

/**
 *	This is a Java bean auto-generated by underlying framework. <br/>
 *	<p>
 *  This Java bean corresponds to a table in a database.
 *  </p>
 *	
 *  @Description 每个模型类对应一个数据库中的一张表
 *	@author vinsy
 *  @date 2018/03/23
 */
@Setter
@Getter
public class AuthorizationUser extends Identifiable {

	private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * 用户名称
     * </pre>
     * 
     */
    private String name;

    /**
     * <pre>
     * 密码
     * </pre>
     * 
     */
    private String password;

    /**
     * <pre>
     * </pre>
     * 
     */
    private String attr;

    /**
     * <pre>
     * 真实姓名
     * </pre>
     * 
     */
    private String realName;

    /**
     * <pre>
     * 性别
     * </pre>
     * 
     */
    private String gender;

    /**
     * <pre>
     * 出生日期
     * </pre>
     * 
     */
    private Date birthday;

    /**
     * <pre>
     * 办公电话
     * </pre>
     * 
     */
    private String officePhone;

    /**
     * <pre>
     * 手机
     * </pre>
     * 
     */
    private String mobilePhone;

    /**
     * <pre>
     * 家庭电话
     * </pre>
     * 
     */
    private String homePhone;

    /**
     * <pre>
     * 电子邮件
     * </pre>
     * 
     */
    private String email;

    /**
     * <pre>
     * 备注
     * </pre>
     * 
     */
    private String remark;

    /**
     * <pre>
     * 创建者Id
     * </pre>
     * 
     */
    private Long creator;

    /**
     * <pre>
     * 状态：激活、停用、删除
     * </pre>
     * 
     */
    private String status;

    /**
     * <pre>
     * 创建时间
     * </pre>
     * 
     */
    private Date createTime;

    /**
     * <pre>
     * 用户号码
     * </pre>
     * 
     */
    private String code;

    /**
     * <pre>
     * 是否指纹登陆
     * </pre>
     * 
     */
    private String fingerprintLogin;

    /**
     * <pre>
     * 用户登录的方式  单客户端登陆  多客户端登录
     * </pre>
     * 
     */
    private String allowLoginType;

    /**
     * <pre>
     * 是否内部员工
     * </pre>
     * 
     */
    private String isInternalEmployee;

    /**
     * <pre>
     * </pre>
     * 
     */
    private Object extendedField;

    /**
     * <pre>
     * </pre>
     * 
     */
    private Date updateTime;

    /**
     * <pre>
     * 权限模块用户唯一ID：可取代主键ID用于查询或关联等
     * </pre>
     * 
     */
    private String userId;

}
