server:
  port: 13579
  context-path: /spring-boot-application
  servlet-path: /api
  tomcat:
    max-threads: 200
    accept-count: 100
    max-connections: 300
    
spring:
  profiles: local
  
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://localhost:5432/xyes
    username: postgres
    password: postgres
    max-idle: 10
    max-wait: 10000
    maximum-pool-size: 30
    max-active: 15
    min-idle: 5