package application.io.spring.bottomware.authorization.business.provider.service;

import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import net.sf.json.JSONObject;
import org.springframework.stereotype.Service;

import application.io.spring.bottomware.authorization.business.api.model.AuthorizationRoleResource;
import application.io.spring.bottomware.authorization.business.api.service.AuthorizationRoleResourceService;
import application.io.spring.bottomware.authorization.business.provider.dao.AuthorizationRoleResourceDAO;
import application.io.spring.common.utils.json.GsonUtils;
import application.io.spring.core.base.api.vo.PageVo;
import application.io.spring.core.base.provider.service.BaseServiceImpl;

/**
 *	This is a service implementation class auto-generated by underlying framework. <br/>
 *	<p>
 *  This class can be modified according to business requirement.
 *  </p>
 *	
 *  @Description 该服务接口实现类的内容可根据实际业务需求调整
 *	@author vinsy
 *  @date 2018/03/23
 */
@Service("authorizationRoleResourceService")
public class AuthorizationRoleResourceServiceImpl extends BaseServiceImpl<AuthorizationRoleResource> implements AuthorizationRoleResourceService {

	@Resource
    private AuthorizationRoleResourceDAO authorizationRoleResourceDAO;

	// 根据jsonb条件查询分页数据
	@SuppressWarnings("unchecked")
	@Override
	public PageVo<AuthorizationRoleResource> getJsonbPageableList(AuthorizationRoleResource authorizationRoleResource,Long offset, Long limit, String orderby){
		Map<String,Object> params = new HashMap<String,Object>();
		if (authorizationRoleResource != null) {
    		params = GsonUtils.GSON.fromJson(GsonUtils.GSON.toJson(authorizationRoleResource), Map.class); 
    	}

		// 将json字符串转为map并将其作为查询条件
		JSONObject  jasonObject0 = JSONObject.fromObject(authorizationRoleResource.getExtendedField());
		Map<String,Object> map0 = (Map<String,Object>)jasonObject0;
		for (Map.Entry<String,Object> entry0 : map0.entrySet()) {
		    params.put(entry0.getKey(), entry0.getValue());
		}
		params = this.getCondition(params, offset, limit, orderby);
    	PageVo<AuthorizationRoleResource> pageVo = this.getPageVo(params);
    	pageVo.setRows(authorizationRoleResourceDAO.getJsonbPageableList(params));
    	pageVo.setTotal(authorizationRoleResourceDAO.getJsonbListCount(params));
    	return pageVo;
	}
}
