package application.io.spring.bottomware.authorization.business.provider.service;

import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import net.sf.json.JSONObject;
import org.springframework.stereotype.Service;

import application.io.spring.bottomware.authorization.business.api.model.AuthorizationResource;
import application.io.spring.bottomware.authorization.business.api.service.AuthorizationResourceService;
import application.io.spring.bottomware.authorization.business.provider.dao.AuthorizationResourceDAO;
import application.io.spring.common.utils.json.GsonUtils;
import application.io.spring.core.base.api.vo.PageVo;
import application.io.spring.core.base.provider.service.BaseServiceImpl;

/**
 *	This is a service implementation class auto-generated by underlying framework. <br/>
 *	<p>
 *  This class can be modified according to business requirement.
 *  </p>
 *	
 *  @Description 该服务接口实现类的内容可根据实际业务需求调整
 *	@author vinsy
 *  @date 2018/03/23
 */
@Service("authorizationResourceService")
public class AuthorizationResourceServiceImpl extends BaseServiceImpl<AuthorizationResource> implements AuthorizationResourceService {

	@Resource
    private AuthorizationResourceDAO authorizationResourceDAO;

	// 根据jsonb条件查询分页数据
	@SuppressWarnings("unchecked")
	@Override
	public PageVo<AuthorizationResource> getJsonbPageableList(AuthorizationResource authorizationResource,Long offset, Long limit, String orderby){
		Map<String,Object> params = new HashMap<String,Object>();
		if (authorizationResource != null) {
    		params = GsonUtils.GSON.fromJson(GsonUtils.GSON.toJson(authorizationResource), Map.class); 
    	}

		// 将json字符串转为map并将其作为查询条件
		JSONObject  jasonObject0 = JSONObject.fromObject(authorizationResource.getExtendedField());
		Map<String,Object> map0 = (Map<String,Object>)jasonObject0;
		for (Map.Entry<String,Object> entry0 : map0.entrySet()) {
		    params.put(entry0.getKey(), entry0.getValue());
		}
		params = this.getCondition(params, offset, limit, orderby);
    	PageVo<AuthorizationResource> pageVo = this.getPageVo(params);
    	pageVo.setRows(authorizationResourceDAO.getJsonbPageableList(params));
    	pageVo.setTotal(authorizationResourceDAO.getJsonbListCount(params));
    	return pageVo;
	}
}
